mutation CreateUser($email: String!, $username: String!) @auth(level: USER) {
  user_insert(data: { email: $email, username: $username, createdAt_expr: "request.time" })
}

query GetUser($id: UUID!) @auth(level: USER) {
  user(id: $id) {
    id
    email
    username
    createdAt
  }
}

mutation CreateMessage($conversationId: UUID!, $content: String!, $senderType: String!) @auth(level: USER) {
  message_insert(data: { conversationId: $conversationId, content: $content, senderType: $senderType, sentAt_expr: "request.time", userId_expr: "auth.uid" })
}

query ListMessagesByConversation($conversationId: UUID!) @auth(level: USER) {
  messages(where: { conversationId: { eq: $conversationId } }) {
    id
    content
    sentAt
    senderType
  }
}